### ISSUE TITLE
Run latest mocha

### ISSUE THREAD

**Issue by nbasov** [mmotkina/mocha-parallel-tests#20]
Hello,

I need to run latest mocha in parallel. As I see you defined mocha version in package.json "dependencies" section. May be it will be better to move mocha to devDependencies.

What solution do you see to run latest mocha?

**Comment by 1999** [comment]
Hello @nbasov 

mocha can't be moved into devDependencies because it's actively used inside mocha-parallel-tests itself: https://github.com/mmotkina/mocha-parallel-tests/blob/master/lib/watcher.js#L99
If we move mocha into devDependencies it won't be installed on `npm install mocha-parallel-tests`.

Possible solution could be moving mocha into `peerDependencies`, but this would make every user of `mocha-parallel-tests` also install `mocha` package and if some breaking changes happen inside mocha, any error can occur.

Current strict dependency allows us to be sure that all tests written with mocha-parallel-tests will run as expected. Also it's pretty simple for us to update mocha to the latest version. So this is currently considered to be the best solution: use strict version and update mocha as soon as new release appears.

**Comment by 1999** [comment]
I'll merge #21 asap if tests don't fail

**Comment by 1999** [comment]
Done: https://github.com/mmotkina/mocha-parallel-tests/blob/master/CHANGELOG.md

**Comment by nbasov** [comment]
Got it. Thank you!
