### ISSUE TITLE
ReferenceError: driver is not defined

### ISSUE THREAD

**Issue by diemol** [mmotkina/mocha-parallel-tests#30]
Hi,

I am trying to use the `mocha-parallel-tests` npm package with the following test suite:
https://github.com/diemol/frontend_testing/tree/master/webdriver-examples-js-parallel

The suite works fine when I just use `mocha`, and of course it runs sequentially.

When I try to use `./node_modules/.bin/mocha-parallel-tests test/`, I get the following:

```
  1) Book hotel and select pay at hotel should leave booking reserved

  2) Register user should leave new user logged in

  0 passing (78ms)
  2 failing

  1)  Book hotel and select pay at hotel should leave booking reserved:
     ReferenceError: driver is not defined
      at Context.<anonymous> (test/hotel.js:15:25)

  2)  Register user should leave new user logged in:
     ReferenceError: driver is not defined
      at Context.<anonymous> (test/user.js:16:9)
```

So it seems that when `mocha` is executed, somehow the path location of the test is ignored or replaced by a new one.

I am not a JavaScript expert, but maybe the error could be around here? https://github.com/mmotkina/mocha-parallel-tests/blob/master/lib/watcher.js#L109

Is there a way I can turn on the debug? I tried reading the code but it was not so easy to understand for me.

I appreciate any help, thanks!

**Comment by 1999** [comment]
I would say that the problem lies somewhere here: https://github.com/diemol/frontend_testing/blob/master/webdriver-examples-js-parallel/test/base.js#L34
You are creating a `driver` variable without `var`, `let` or `const`. This usually means that the variable is created in the global scope and is considered to be a buggy behaviour, which is why this is prohibited in strict mode.

Anyway if you want `driver` variable to be accessed inside hotels test, you can create `driver` with `var driver = ...` and pass it as the only argument to callback function [here](https://github.com/diemol/frontend_testing/blob/master/webdriver-examples-js-parallel/test/base.js#L52). In this case it would be accessible as the first argument of a function [here](https://github.com/diemol/frontend_testing/blob/master/webdriver-examples-js-parallel/test/hotel.js#L11). I guess this should work.

**Comment by diemol** [comment]
Hi again,

What you said makes a lot of sense, also because the `driver` variable will be shared by the tests and this leads usually to unexpected behaviour. 
I have done the same example in Java, and a `ThreadLocal` array is used or creating the `driver` in the test. 
The same concept should apply here, I will refactor my examples to reflect it.

I'll close the issue since it is clearly related to the code and not the package.

Thanks for your feedback!

**Comment by 1999** [comment]
No worries, thanks for using mocha-parallel-tests.
